import { Country, Difficulty } from './types';

/**
 * GUIDE FÖR BILDER:
 * 1. Skapa en mapp som heter 'public' i din rotmapp.
 * 2. Skapa en mapp inuti den som heter 'images'.
 * 3. Lägg dina bilder där (t.ex. 'france.jpg').
 * 4. Ändra sökvägen nedan till '/images/ditt_filnamn.jpg'.
 * 
 * Exempel: imageUrl: '/images/france.jpg'
 */

export const countries: Country[] = [
  // EASY (Difficulty 1)
  { id: '1', name: 'Albania' , difficulty: Difficulty.EASY, imageUrl: '/images/albania.jpg' },
  { id: '2', name: 'Australia' , difficulty: Difficulty.EASY, imageUrl: '/images/australia.png' },
  { id: '3', name: 'Austria' , difficulty: Difficulty.EASY, imageUrl: '/images/austria.jpg' },
  { id: '4', name: 'Belgium' , difficulty: Difficulty.EASY, imageUrl: '/images/belgium.jpg' },
  { id: '5', name: 'Brazil' , difficulty: Difficulty.EASY, imageUrl: '/images/brazil.png' },
  { id: '6', name: 'Cambodia' , difficulty: Difficulty.EASY, imageUrl: '/images/cambodia.png' },
  { id: '7', name: 'Canada' , difficulty: Difficulty.EASY, imageUrl: '/images/canada.jpg' },
  { id: '8', name: 'China' , difficulty: Difficulty.EASY, imageUrl: '/images/china.png' },
  { id: '9', name: 'Colombia' , difficulty: Difficulty.EASY, imageUrl: '/images/colombia.jpg' },
  { id: '10', name: 'Czech Republic' , difficulty: Difficulty.EASY, imageUrl: '/images/czech_republic.jpg' },
  { id: '11', name: 'Denmark' , difficulty: Difficulty.EASY, imageUrl: '/images/denmark.jpg' },
  { id: '12', name: 'Egypt' , difficulty: Difficulty.EASY, imageUrl: '/images/egypt.png' },
  { id: '13', name: 'Estonia' , difficulty: Difficulty.EASY, imageUrl: '/images/estonia.jpg' },
  { id: '14', name: 'Finland' , difficulty: Difficulty.EASY, imageUrl: '/images/finland.jpg' },
  { id: '15', name: 'France' , difficulty: Difficulty.EASY, imageUrl: '/images/france.jpg' },
  { id: '16', name: 'Germany' , difficulty: Difficulty.EASY, imageUrl: '/images/germany.jpg' },
  { id: '17', name: 'Greece' , difficulty: Difficulty.EASY, imageUrl: '/images/greece.jpg' },
  { id: '18', name: 'Hungary' , difficulty: Difficulty.EASY, imageUrl: '/images/hungary.jpg' },
  { id: '19', name: 'Iceland' , difficulty: Difficulty.EASY, imageUrl: '/images/iceland.jpg' },
  { id: '20', name: 'India' , difficulty: Difficulty.EASY, imageUrl: '/images/india.png' },
  { id: '21', name: 'Ireland' , difficulty: Difficulty.EASY, imageUrl: '/images/ireland.jpg' },
  { id: '22', name: 'Israel' , difficulty: Difficulty.EASY, imageUrl: '/images/israel.jpg' },
  { id: '23', name: 'Italy' , difficulty: Difficulty.EASY, imageUrl: '/images/italy.jpg' },
  { id: '24', name: 'Jamaica' , difficulty: Difficulty.EASY, imageUrl: '/images/jamaica.jpg' },
  { id: '25', name: 'Japan' , difficulty: Difficulty.EASY, imageUrl: '/images/japan.png' },
  { id: '26', name: 'Luxembourg' , difficulty: Difficulty.EASY, imageUrl: '/images/luxembourg.jpg' },
  { id: '27', name: 'Madagaskar' , difficulty: Difficulty.EASY, imageUrl: '/images/madagaskar.jpg' },
  { id: '28', name: 'Malaysia' , difficulty: Difficulty.EASY, imageUrl: '/images/malaysia.jpg' },
  { id: '29', name: 'Mexico' , difficulty: Difficulty.EASY, imageUrl: '/images/mexico.jpg' },
  { id: '30', name: 'Monaco' , difficulty: Difficulty.EASY, imageUrl: '/images/monaco.jpg' },
  { id: '31', name: 'Netherlands' , difficulty: Difficulty.EASY, imageUrl: '/images/netherlands.jpg' },
  { id: '32', name: 'New Zealand' , difficulty: Difficulty.EASY, imageUrl: '/images/new_zealand.png' },
  { id: '33', name: 'North Korea' , difficulty: Difficulty.EASY, imageUrl: '/images/north_korea.png' },
  { id: '34', name: 'Norway' , difficulty: Difficulty.EASY, imageUrl: '/images/norway.jpg' },
  { id: '35', name: 'Panama' , difficulty: Difficulty.EASY, imageUrl: '/images/panama.jpg' },
  { id: '36', name: 'Peru' , difficulty: Difficulty.EASY, imageUrl: '/images/peru.jpg' },
  { id: '37', name: 'Portugal' , difficulty: Difficulty.EASY, imageUrl: '/images/portugal.jpg' },
  { id: '38', name: 'Romania' , difficulty: Difficulty.EASY, imageUrl: '/images/romania.jpg' },
  { id: '39', name: 'Russia' , difficulty: Difficulty.EASY, imageUrl: '/images/russia.png' },
  { id: '40', name: 'Singapore' , difficulty: Difficulty.EASY, imageUrl: '/images/singapore.png' },
  { id: '41', name: 'South Africa' , difficulty: Difficulty.EASY, imageUrl: '/images/south_africa.jpg' },
  { id: '42', name: 'Spain' , difficulty: Difficulty.EASY, imageUrl: '/images/spain.jpg' },
  { id: '43', name: 'Sweden' , difficulty: Difficulty.EASY, imageUrl: '/images/sweden.jpg' },
  { id: '44', name: 'Switzerland' , difficulty: Difficulty.EASY, imageUrl: '/images/switzerland.jpg' },
  { id: '45', name: 'Turkey' , difficulty: Difficulty.EASY, imageUrl: '/images/turkey.jpg' },
  { id: '46', name: 'Uae' , difficulty: Difficulty.EASY, imageUrl: '/images/uae.jpg' },
  { id: '47', name: 'United Kingdom' , difficulty: Difficulty.EASY, imageUrl: '/images/united_kingdom.jpg' },
  { id: '48', name: 'Usa' , difficulty: Difficulty.EASY, imageUrl: '/images/usa.jpg' },
  { id: '49', name: 'Vatican' , difficulty: Difficulty.EASY, imageUrl: '/images/vatican.png' },



  // MEDIUM (Difficulty 2)
  { id: '50', name: 'Argentina' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/argentina.png' },
  { id: '51', name: 'Azerbaijan' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/azerbaijan.jpg' },
  { id: '52', name: 'Bahamas' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/bahamas.png' },
  { id: '53', name: 'Bhutan' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/bhutan.jpg' },
  { id: '54', name: 'Bulgaria' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/bulgaria.jpg' },
  { id: '55', name: 'Chile' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/chile.jpg' },
  { id: '56', name: 'Croatia' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/croatia.jpg' },
  { id: '57', name: 'Ecuador' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/ecuador.jpg' },
  { id: '58', name: 'Indonesia' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/indonesia.jpg' },
  { id: '59', name: 'Iran' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/iran.jpg' },
  { id: '60', name: 'Jordan' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/jordan.jpg' },
  { id: '61', name: 'Kenya' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/kenya.jpg' },
  { id: '62', name: 'Latvia' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/latvia.jpg' },
  { id: '63', name: 'Liechtenstein' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/liechtenstein.jpg' },
  { id: '64', name: 'Lithuania' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/lithuania.jpg' },
  { id: '65', name: 'Maldives' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/maldives.jpg' },
  { id: '66', name: 'Malta' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/malta.jpg' },
  { id: '67', name: 'Mauritius' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/mauritius.jpg' },
  { id: '68', name: 'Mongolia' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/mongolia.png' },
  { id: '69', name: 'Morocco' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/morocco.jpg' },
  { id: '70', name: 'Myanmar' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/myanmar.jpg' },
  { id: '71', name: 'Namibia' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/namibia.jpg' },
  { id: '72', name: 'Nepal' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/nepal.jpg' },
  { id: '73', name: 'Poland' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/poland.jpg' },
  { id: '74', name: 'Saudi Arabia' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/saudi_arabia.jpg' },
  { id: '75', name: 'Seychelles' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/seychelles.jpg' },
  { id: '76', name: 'Slovenia' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/slovenia.jpg' },
  { id: '77', name: 'South Korea' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/south_korea.png' },
  { id: '78', name: 'Sri Lanka' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/sri_lanka.jpg' },
  { id: '79', name: 'Tanzania' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/tanzania.jpg' },
  { id: '80', name: 'Thailand' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/thailand.png' },
  { id: '81', name: 'Turkmenistan' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/turkmenistan.jpg' },
  { id: '82', name: 'Ukraine' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/ukraine.jpg' },
  { id: '83', name: 'Vietnam' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/vietnam.png' },
  { id: '84', name: 'Zimbabwe' , difficulty: Difficulty.MEDIUM, imageUrl: '/images/zimbabwe.jpg' },


  // HARD (Difficulty 3)
  { id: '85', name: 'Afghanistan' , difficulty: Difficulty.HARD, imageUrl: '/images/afghanistan.png' },
  { id: '86', name: 'Algeria' , difficulty: Difficulty.HARD, imageUrl: '/images/algeria.png' },
  { id: '87', name: 'Armenia' , difficulty: Difficulty.HARD, imageUrl: '/images/armenia.png' },
  { id: '88', name: 'Bahrain' , difficulty: Difficulty.HARD, imageUrl: '/images/bahrain.jpg' },
  { id: '89', name: 'Bangladesh' , difficulty: Difficulty.HARD, imageUrl: '/images/bangladesh.jpg' },
  { id: '90', name: 'Belarus' , difficulty: Difficulty.HARD, imageUrl: '/images/belarus.jpg' },
  { id: '91', name: 'Belize' , difficulty: Difficulty.HARD, imageUrl: '/images/belize.jpg' },
  { id: '92', name: 'Botswana' , difficulty: Difficulty.HARD, imageUrl: '/images/botswana.jpg' },
  { id: '93', name: 'Brunei' , difficulty: Difficulty.HARD, imageUrl: '/images/brunei.png' },
  { id: '94', name: 'Cuba' , difficulty: Difficulty.HARD, imageUrl: '/images/cuba.jpg' },
  { id: '95', name: 'Djibouti' , difficulty: Difficulty.HARD, imageUrl: '/images/djibouti.jpg' },
  { id: '96', name: 'Eritrea' , difficulty: Difficulty.HARD, imageUrl: '/images/eritrea.jpg' },
  { id: '97', name: 'Ethiopia' , difficulty: Difficulty.HARD, imageUrl: '/images/ethiopia.jpg' },
  { id: '98', name: 'Gabon' , difficulty: Difficulty.HARD, imageUrl: '/images/gabon.jpg' },
  { id: '99', name: 'Georgia' , difficulty: Difficulty.HARD, imageUrl: '/images/georgia.jpg' },
  { id: '100', name: 'Iraq' , difficulty: Difficulty.HARD, imageUrl: '/images/iraq.jpg' },
  { id: '101', name: 'Kazakhstan' , difficulty: Difficulty.HARD, imageUrl: '/images/kazakhstan.jpg' },
  { id: '102', name: 'Kuwait' , difficulty: Difficulty.HARD, imageUrl: '/images/kuwait.jpg' },
  { id: '103', name: 'Kyrgyzstan' , difficulty: Difficulty.HARD, imageUrl: '/images/kyrgyzstan.jpg' },
  { id: '104', name: 'Laos' , difficulty: Difficulty.HARD, imageUrl: '/images/laos.png' },
  { id: '105', name: 'Lesotho' , difficulty: Difficulty.HARD, imageUrl: '/images/lesotho.jpg' },
  { id: '106', name: 'Montenegro' , difficulty: Difficulty.HARD, imageUrl: '/images/montenegro.jpg' },
  { id: '107', name: 'Pakistan' , difficulty: Difficulty.HARD, imageUrl: '/images/pakistan.jpg' },
  { id: '108', name: 'Palau' , difficulty: Difficulty.HARD, imageUrl: '/images/palau.jpg' },
  { id: '109', name: 'Paraguay' , difficulty: Difficulty.HARD, imageUrl: '/images/paraguay.jpg' },
  { id: '110', name: 'Philippines' , difficulty: Difficulty.HARD, imageUrl: '/images/philippines.png' },
  { id: '111', name: 'Qatar' , difficulty: Difficulty.HARD, imageUrl: '/images/qatar.jpg' },
  { id: '112', name: 'San Marino' , difficulty: Difficulty.HARD, imageUrl: '/images/san_marino.jpg' },
  { id: '113', name: 'Serbia' , difficulty: Difficulty.HARD, imageUrl: '/images/serbia.jpg' },
  { id: '114', name: 'Slovakia' , difficulty: Difficulty.HARD, imageUrl: '/images/slovakia.jpg' },
  { id: '115', name: 'Syria' , difficulty: Difficulty.HARD, imageUrl: '/images/syria.jpg' },
  { id: '116', name: 'Tajikistan' , difficulty: Difficulty.HARD, imageUrl: '/images/tajikistan.jpg' },
  { id: '117', name: 'Tonga' , difficulty: Difficulty.HARD, imageUrl: '/images/tonga.jpg' },
  { id: '118', name: 'Trinidad And Tobago' , difficulty: Difficulty.HARD, imageUrl: '/images/trinidad_and_tobago.jpg' },
  { id: '119', name: 'Tunisia' , difficulty: Difficulty.HARD, imageUrl: '/images/tunisia.jpg' },
  { id: '120', name: 'Uruguay' , difficulty: Difficulty.HARD, imageUrl: '/images/uruguay.jpg' },
  { id: '121', name: 'Uzbekistan' , difficulty: Difficulty.HARD, imageUrl: '/images/uzbekistan.jpg' },
  { id: '122', name: 'Venezuela' , difficulty: Difficulty.HARD, imageUrl: '/images/venezuela.png' },
  { id: '123', name: 'Yemen' , difficulty: Difficulty.HARD, imageUrl: '/images/yemen.jpg' },

];